- name: Install the python module psycopg2
  ansible.builtin.package:
    name: python3-psycopg2
    state: present

- name: Install PostgreSQL
  ansible.builtin.package:
    name: postgresql
    state: present
  become: yes

- name: Run and enabled the service
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes

- name: Replace ipaddress in pg_hba.conf
  ansible.builtin.lineinfile:
    path: /etc/postgresql/15/main/pg_hba.conf
    regexp: '^host\s+all\s+all\s+127\.0\.0\.1\/32'
    line: 'host    all             all             0.0.0.0/0                 trust'
    state: present
  notify: Restart PostgreSQL
  become: yes

- name: Replace peer to trust pg_hba.conf
  ansible.builtin.lineinfile:
    path: /etc/postgresql/15/main/pg_hba.conf
    regexp: '^local\s+all\s+postgres\s+peer'
    line: 'local   all             postgres                                trust'
    state: present
  notify: Restart PostgreSQL
  become: yes
  become_user: postgres

  
- name: Trust auth for users
  ansible.builtin.lineinfile:
    path: /etc/postgresql/15/main/pg_hba.conf
    regexp: '^local\s+all\s+all\s+peer'
    line: 'local   all             all                                     trust'
    state: present
  notify: Restart PostgreSQL
  become: yes
  become_user: postgres

- name: Create databases
  ansible.builtin.postgresql_db:
    name: "{{ item }}"
    state: present
  loop:
    - all
    - dev
    - stage
    - prod
  become: yes
  become_user: postgres

- name: Create user 'vagrant' with superuser privileges
  ansible.builtin.postgresql_user:
    name: vagrant
    password: "PasswordDb"
    role_attr_flags: SUPERUSER
    state: present
  become: yes
  become_user: postgres


- name: Grant privileges to vagrant for DB all
  ansible.builtin.postgresql_privs:
    database: all
    roles: vagrant
    type: database
    privs: ALL
    state: present
  become: yes
  become_user: postgres


- name: Assign 'vagrant' as owner of databases
  ansible.builtin.postgresql_db:
    name: "{{ item }}"
    owner: vagrant
  loop:
    - dev
    - stage
    - prod
  become: yes
  become_user: postgres

